<?xml version="1.0"?>

<!DOCTYPE AtlantisConfiguration [

<!ELEMENT AtlantisConfiguration (Initialization, Parameters,ParameterDifferences*, WindowCorners*)>

<!ELEMENT Initialization (Interactions, Canvas)>

<!ELEMENT Interactions (Panel*, InteractionControl+)>

<!ELEMENT InteractionControl (Panel*)>
    <!ATTLIST InteractionControl
        projectionName    CDATA #REQUIRED
        availableInDemoMode     CDATA "YES"
        defaultInDemoMode CDATA "NO" >

<!ELEMENT Panel EMPTY>
    <!ATTLIST Panel
        screenName CDATA #REQUIRED
        fileName   CDATA #REQUIRED
        toolTip    CDATA "">

<!ELEMENT Canvas (UsedWindow+, Layout+)>
    <!ATTLIST Canvas
        startupLayout CDATA #REQUIRED
        aspectRatio   CDATA #REQUIRED>

<!ELEMENT UsedWindow EMPTY>
    <!ATTLIST UsedWindow
        name       CDATA #REQUIRED
        projection CDATA "EP"
        group      CDATA "Data">

<!ELEMENT Layout (Window+, Page+)>
    <!ATTLIST Layout
        name          CDATA #REQUIRED
        startup       CDATA #REQUIRED
        startupWindow CDATA #REQUIRED>

<!ELEMENT Window EMPTY>
    <!ATTLIST Window
        name   CDATA #REQUIRED
        hPos   CDATA #REQUIRED
        vPos   CDATA #REQUIRED
        width  CDATA #REQUIRED
        height CDATA #REQUIRED>

<!ELEMENT Page EMPTY>
    <!ATTLIST Page
        name    CDATA #REQUIRED
        content CDATA #REQUIRED>

<!ELEMENT Parameters (SuperGroup*)>
    <!ATTLIST Parameters
        userLevel CDATA #REQUIRED>

<!ELEMENT SuperGroup (Group*)>
    <!ATTLIST SuperGroup
        name    CDATA #REQUIRED
        toolTip CDATA ""
        userLevel CDATA "0">

<!ELEMENT Group (Command*,((ENUM)*, (SENUM)*, (ICUT)*, (SICUT)*, (FCUT)*, (SFCUT)*, (INT)*, (SINT)*,(LINT)*, (SLINT)*, (FLOAT)*, (SFLOAT)*, (COLOR)*, (SCOLOR)*, (StatusRoot)*, (STATUS)*, (LINK)*)* )>
    <!ATTLIST Group
        name      CDATA #REQUIRED
        sname     CDATA ""
        guiUsage  (NO_USE|TABLE|PROJECTION|BRAIN_TEST) "NO_USE"
        scope     (LOCAL|GLOBAL) "GLOBAL"
        userLevel CDATA "0"
        toolTip   CDATA "">

<!ELEMENT Command EMPTY>
    <!ATTLIST Command
        name    CDATA #REQUIRED
        command CDATA #REQUIRED
        ul      CDATA "0"
        toolTip CDATA "">

<!ENTITY none "0">

<!ELEMENT ENUM   EMPTY>	<!ATTLIST ENUM   fn CDATA #REQUIRED sn CDATA "" va CDATA #REQUIRED pv CDATA "-inf : inf"                                                                           tip CDATA "" ul CDATA "0" scope CDATA "">
<!ELEMENT SENUM  EMPTY> <!ATTLIST SENUM  fn CDATA #REQUIRED sn CDATA "" va CDATA #REQUIRED pv CDATA "-inf : inf" st (ON|OFF) #REQUIRED                                                     tip CDATA "" ul CDATA "0" scope CDATA "">
<!ELEMENT ICUT   EMPTY> <!ATTLIST ICUT   fn CDATA #REQUIRED sn CDATA "" va CDATA #REQUIRED pv CDATA "-inf : inf"                       isMod (YES|NO) "NO" op CDATA #REQUIRED dop CDATA "" tip CDATA "" ul CDATA "0" scope CDATA "" u CDATA "&none;">
<!ELEMENT SICUT  EMPTY> <!ATTLIST SICUT  fn CDATA #REQUIRED sn CDATA "" va CDATA #REQUIRED pv CDATA "-inf : inf" st (ON|OFF) #REQUIRED isMod (YES|NO) "NO" op CDATA #REQUIRED dop CDATA "" tip CDATA "" ul CDATA "0" scope CDATA "" u CDATA "&none;">
<!ELEMENT FCUT   EMPTY> <!ATTLIST FCUT   fn CDATA #REQUIRED sn CDATA "" va CDATA #REQUIRED pv CDATA "-inf : inf"                       isMod (YES|NO) "NO" op CDATA #REQUIRED dop CDATA "" tip CDATA "" ul CDATA "0" scope CDATA "" u CDATA "&none;">
<!ELEMENT SFCUT  EMPTY> <!ATTLIST SFCUT  fn CDATA #REQUIRED sn CDATA "" va CDATA #REQUIRED pv CDATA "-inf : inf" st (ON|OFF) #REQUIRED isMod (YES|NO) "NO" op CDATA #REQUIRED dop CDATA "" tip CDATA "" ul CDATA "0" scope CDATA "" u CDATA "&none;">
<!ELEMENT INT    EMPTY> <!ATTLIST INT    fn CDATA #REQUIRED sn CDATA "" va CDATA #REQUIRED pv CDATA "-inf : inf"                       isMod (YES|NO) "NO"                                 tip CDATA "" ul CDATA "0" scope CDATA "" u CDATA "&none;">
<!ELEMENT SINT   EMPTY> <!ATTLIST SINT   fn CDATA #REQUIRED sn CDATA "" va CDATA #REQUIRED pv CDATA "-inf : inf" st (ON|OFF) #REQUIRED isMod (YES|NO) "NO"                                 tip CDATA "" ul CDATA "0" scope CDATA "" u CDATA "&none;">
<!ELEMENT FLOAT  EMPTY> <!ATTLIST FLOAT  fn CDATA #REQUIRED sn CDATA "" va CDATA #REQUIRED pv CDATA "-inf : inf"                       isMod (YES|NO) "NO"                                 tip CDATA "" ul CDATA "0" scope CDATA "" u CDATA "&none;">
<!ELEMENT SFLOAT EMPTY> <!ATTLIST SFLOAT fn CDATA #REQUIRED sn CDATA "" va CDATA #REQUIRED pv CDATA "-inf : inf" st (ON|OFF) #REQUIRED isMod (YES|NO) "NO"                                 tip CDATA "" ul CDATA "0" scope CDATA "" u CDATA "&none;">
<!ELEMENT LINT   EMPTY> <!ATTLIST LINT   fn CDATA #REQUIRED sn CDATA "" va CDATA #REQUIRED pv CDATA "-inf : inf"                                                                           tip CDATA "" ul CDATA "0" scope CDATA "" u CDATA "&none;">
<!ELEMENT SLINT  EMPTY> <!ATTLIST SLINT  fn CDATA #REQUIRED sn CDATA "" va CDATA #REQUIRED pv CDATA "-inf : inf" st (ON|OFF) #REQUIRED                                                     tip CDATA "" ul CDATA "0" scope CDATA "" u CDATA "&none;">
<!ELEMENT COLOR  EMPTY> <!ATTLIST COLOR  fn CDATA #REQUIRED sn CDATA "" va CDATA #REQUIRED pv CDATA "-inf : inf"                                                                           tip CDATA "" ul CDATA "0" scope CDATA "">
<!ELEMENT SCOLOR EMPTY> <!ATTLIST SCOLOR fn CDATA #REQUIRED sn CDATA "" va CDATA #REQUIRED pv CDATA "-inf : inf" st (ON|OFF) #REQUIRED                                                     tip CDATA "" ul CDATA "0" scope CDATA "">
<!ELEMENT StatusRoot (StatusGroup*, STATUS*)>  <!ATTLIST StatusRoot  fn CDATA #REQUIRED sn CDATA "" st (ON|OFF) "OFF"     tip CDATA "" ul CDATA "0" scope CDATA "">
<!ELEMENT StatusGroup (StatusGroup*, STATUS*)> <!ATTLIST StatusGroup fn CDATA #REQUIRED sn CDATA "" st (ON|OFF) "OFF"     tip CDATA "" ul CDATA "0" scope CDATA "">
<!ELEMENT STATUS EMPTY>                        <!ATTLIST STATUS      fn CDATA #REQUIRED sn CDATA "" st (ON|OFF) #REQUIRED tip CDATA "" ul CDATA "0" scope CDATA "">
<!ELEMENT LINK   EMPTY> <!ATTLIST LINK to CDATA #REQUIRED>

<!ELEMENT ParameterDifferences (DIFFERENCE*)>

<!ELEMENT DIFFERENCE EMPTY>
    <!ATTLIST DIFFERENCE
        group      CDATA #REQUIRED
        name       CDATA #REQUIRED
        windowName CDATA #REQUIRED
        va         CDATA ""
        st         CDATA "" 
        op         CDATA "">

<!ELEMENT WindowCorners (CORNERS*)>

<!ELEMENT CORNERS EMPTY>
    <!ATTLIST CORNERS
        windowName CDATA #REQUIRED
        x0         CDATA #REQUIRED
        y0         CDATA #REQUIRED
        x1         CDATA #REQUIRED
        y1         CDATA #REQUIRED
        x2         CDATA #REQUIRED
        y2         CDATA #REQUIRED>

<!ENTITY length "1">
<!ENTITY energy "2">
<!ENTITY energyMEV "3">

<!ENTITY user "0">
<!ENTITY superuser "1">
<!ENTITY debug "3">

<!ENTITY assocCutOptions "All=0, Connected=1, Unconnected=2">
<!ENTITY drawTo          "Pixels = 0, Silicon Strips = 1, TRT_DriftCircle=2, LAr = 3, TILE = 4, Muon System = 5">
<!ENTITY colorFn         "Constant = 0, Simulated Track = 1, Reconstructed Track = 2, SubDetector = 3, Track Segment = 4">
<!ENTITY colorFnTRT      "Constant = 0, Simulated Track = 1, Reconstructed Track = 2, SubDetector = 3, Track Segment = 4, isOutlier = 5, driftSign = 6, threshold = 7">
<!ENTITY colorFnMTr      "Constant = 0, Index = 1, Pt = 2">
<!ENTITY colorFnCal      "Constant = 0, SubDetector = 1, Cluster = 2, Layer = 3, Energy = 4, Jet = 5, ECAL/HCAL = 6, Time = 7">
<!ENTITY colorFnS3D      "Constant = 0, Simulated Track = 1, Reconstructed Track = 2, SubDetector = 3, Group = 4, Layer = 5">
<!ENTITY colorFnTrigS3D  "Constant = 0, Simulated Track = 1, Reconstructed Track = 2, SubDetector = 3, Layer = 4">
<!ENTITY colorFnSiCluster "Constant = 0, Simulated Track = 1, Reconstructed Track = 2, SubDetector = 3, Layer = 4, Orientation=5">
<!ENTITY colorFnPixCluster "Constant = 0, Simulated Track = 1, Reconstructed Track = 2, SubDetector = 3, Layer = 4, Orientation=5, dE/dx=6">
<!ENTITY colorFnSTr      "Constant = 0, Index = 1, Pt = 2, Particle Type = 3, Origin Vertex = 4">
<!ENTITY colorFnRTr      "Constant = 0, Index = 1, Pt = 2, Collection = 3, Simulated Track = 4, RecVertex = 5, Jet = 6, Objects = 7">
<!ENTITY colorFnBasic    "Constant = 0, Index = 1">
<!ENTITY colorFnBasicCollection "Constant = 0, Index = 1, Collection = 2">

<!ENTITY energyMode      "Sum (Linear) = 0, Max (Linear) = 1, Sum (Logarithmic) = 2, Max (Logarithmic) = 3, Sum (Square Root) = 4, Max (Square Root) = 5">
<!ENTITY symbol          "Filled Square=0, Horizontal Line=1,Vertical Line=2,Plus=3">
<!ENTITY pickingModes    "Event Data=0, Detectors=1">
<!ENTITY frameCol        "0,8:14">
<!ENTITY detectCol       "0:8,14">
<!ENTITY dataCol         "0,8,14:28">
<!ENTITY histoCol        "0,8,14:28">
<!ENTITY real            "&lt;,&gt;">
<!ENTITY eta             "&#x03B7;">
<!ENTITY rho             "&#x03C1;">
<!ENTITY phi             "&#x03A6;">
<!ENTITY delta           "&#x0394;">
<!ENTITY lambda          "&#x03BB;">
<!ENTITY sigma           "&#x03C3;">
<!ENTITY prime           "'">
<!ENTITY ne              "!=">
<!ENTITY le              "&lt;=">
<!ENTITY ge              "&gt;=">
<!ENTITY int             "=,&ne;,&lt;,&le;,&gt;,&ge;">
<!ENTITY intEqual        "=">
<!ENTITY modesFZ         "Standard = 0, RPC Middle 1 = 1, RPC Middle 2 = 2, RPC Outer = 3, MDT Inner and Extension = 4, MDT Middle = 5, MDT Outer = 6">
<!ENTITY modesYX         "Standard = 0, TGC Inner 1 = 1,TGC Middle 1 = 2, TGC Middle 2 = 3, TGC Middle 3 = 4, MDT/CSC Inner 1 = 5, MDT Extension = 6, MDT Middle = 7, MDT Outer = 8, FCAL EM= 9, FCAL HAD 1= 10, FCAL HAD 2= 11, LAr Ecap Presamp= 12, LAr Ecap 1= 13, LAr Ecap 2= 14, LAr Ecap 3= 15, HEC 1= 16, HEC 2= 17, HEC 3= 18, HEC 4= 19, LAr Ecap Summed=20, HEC Summed=21, MBTS=22">

]>

<AtlantisConfiguration>

    <Initialization>

        <Interactions>

            <InteractionControl projectionName="YX" defaultInDemoMode="YES">
                <Panel screenName="ZMR"        fileName="ZMR"            toolTip="Zoom/Move/Rotate"/>
                <Panel screenName="RubberBand" fileName="RubberbandYX"   toolTip="Rubberband Selection"/>
                <Panel screenName="Pick"       fileName="Pick"           toolTip="Show Info for Picked Item"/>
                <Panel screenName="SyncCursors" fileName="SynchroCursors" toolTip="Synchronised Cursors"/>
                <Panel screenName="FishEye"    fileName="FishEye"        toolTip="FishEye Transformation"/>
                <Panel screenName="Clock"      fileName="Clock"          toolTip="Clock Transformation"/>
                <Panel screenName="Scale"      fileName="ScaleCopy"      toolTip="Scale Interaction"/>
            </InteractionControl>

            <InteractionControl projectionName="RZ" defaultInDemoMode="YES">
                <Panel screenName="ZMR"        fileName="ZMR"            toolTip="Zoom/Move/Rotate"/>
                <Panel screenName="RubberBand" fileName="Rubberband"     toolTip="Rubberband Selection"/>
                <Panel screenName="Pick"       fileName="Pick"           toolTip="Show Info for Picked Item"/>
                <Panel screenName="SyncCursors" fileName="SynchroCursors" toolTip="Synchronised Cursors"/>
                <Panel screenName="FishEye"    fileName="FishEye"        toolTip="FishEye Transformation"/>
                <Panel screenName="Skew"       fileName="Skew"           toolTip="Skew Interaction"/>
                <Panel screenName="Scale"      fileName="ScaleCopy"      toolTip="Scale Interaction"/>
            </InteractionControl>

            <InteractionControl projectionName="XZ">
                <Panel screenName="ZMR"        fileName="ZMR"            toolTip="Zoom/Move/Rotate"/>
                <Panel screenName="RubberBand" fileName="Rubberband"     toolTip="Rubberband Selection"/>
                <Panel screenName="Pick"       fileName="Pick"           toolTip="Show Info for Picked Item"/>
                <Panel screenName="SyncCursors" fileName="SynchroCursors" toolTip="Synchronised Cursors"/>
                <Panel screenName="FishEye"    fileName="FishEye"        toolTip="FishEye Transformation"/>
                <Panel screenName="Scale"      fileName="ScaleCopy"      toolTip="Scale Interaction"/>
            </InteractionControl>

            <InteractionControl projectionName="YZ">
                <Panel screenName="ZMR"        fileName="ZMR"            toolTip="Zoom/Move/Rotate"/>
                <Panel screenName="RubberBand" fileName="Rubberband"     toolTip="Rubberband Selection"/>
                <Panel screenName="Pick"       fileName="Pick"           toolTip="Show Info for Picked Item"/>
                <Panel screenName="SyncCursors" fileName="SynchroCursors" toolTip="Synchronised Cursors"/>
                <Panel screenName="FishEye"    fileName="FishEye"        toolTip="FishEye Transformation"/>
                <Panel screenName="Scale"      fileName="ScaleCopy"      toolTip="Scale Interaction"/>
            </InteractionControl>
			
            <InteractionControl projectionName="FZ">
                <Panel screenName="ZMR"        fileName="ZMR"            toolTip="Zoom/Move/Rotate"/>
                <Panel screenName="RubberBand" fileName="Rubberband"     toolTip="Rubberband Selection"/>
                <Panel screenName="Pick"       fileName="Pick"           toolTip="Show Info for Picked Item"/>
                <Panel screenName="SyncCursors" fileName="SynchroCursors" toolTip="Synchronised Cursors"/>
                <Panel screenName="FishEye"    fileName="FishEye"        toolTip="FishEye Transformation"/>
                <Panel screenName="Skew"       fileName="Skew"           toolTip="Skew Interaction"/>
                <Panel screenName="Scale"      fileName="ScaleCopy"      toolTip="Scale Interaction"/>
            </InteractionControl>

            <InteractionControl projectionName="FR">
                <Panel screenName="ZMR"        fileName="ZMR"            toolTip="Zoom/Move/Rotate"/>
                <Panel screenName="RubberBand" fileName="RubberbandYX"     toolTip="Rubberband Selection"/>
                <Panel screenName="Pick"       fileName="Pick"           toolTip="Show Info for Picked Item"/>
                <Panel screenName="SyncCursors" fileName="SynchroCursors" toolTip="Synchronised Cursors"/>
                <Panel screenName="FishEye"    fileName="FishEye"        toolTip="FishEye Transformation"/>
                <Panel screenName="Skew"       fileName="Skew"           toolTip="Skew Interaction"/>
                <Panel screenName="Scale"      fileName="ScaleCopy"      toolTip="Scale Interaction"/>
            </InteractionControl>

            <InteractionControl projectionName="VP" defaultInDemoMode="YES">
                <Panel screenName="RubberBand" fileName="VPSelection"    toolTip="Rubberband Selection"/>
                <Panel screenName="Pick"       fileName="Pick"           toolTip="Show Info for Picked Item"/>
                <Panel screenName="ZMR"        fileName="ZMR"            toolTip="Zoom/Move/Rotate"/>
                <Panel screenName="SyncCursors" fileName="SynchroCursors" toolTip="Synchronised Cursors"/>
                <Panel screenName="Scale"      fileName="ScaleCopy"      toolTip="Scale Interaction"/>
            </InteractionControl>

            <InteractionControl projectionName="3D" availableInDemoMode="NO">
                <Panel screenName="ZMR"        fileName="ZMR"            toolTip="Zoom/Move/Rotate"/>
                <Panel screenName="RubberBand" fileName="VPSelection"    toolTip="Rubberband Selection"/>
                <Panel screenName="Pick"       fileName="Pick"           toolTip="Show Info for Picked Item"/>
                <Panel screenName="FishEye"    fileName="FishEye"        toolTip="FishEye Transformation"/>
                <Panel screenName="SyncCursors" fileName="SynchroCursors" toolTip="Synchronised Cursors"/>
                <Panel screenName="Scale"      fileName="ScaleCopy"      toolTip="Scale Interaction"/>
            </InteractionControl>
			
            <InteractionControl projectionName="3DBox" availableInDemoMode="NO">
                <Panel screenName="ZR"         fileName="3DBox"          toolTip="Zoom/Rotate"/>
                <!-- temporarily remove "Pick" interaction for 3DBox until it is implemented
                <Panel screenName="Pick"       fileName="Pick"           toolTip="Show Info for Picked Item"/>
                -->
            </InteractionControl>

            <InteractionControl projectionName="LegoPlot" >
                <Panel screenName="ZMR"        fileName="ZMR"       	 toolTip="Zoom/Move/Rotate"/>
                <Panel screenName="SyncCursors" fileName="SynchroCursors" toolTip="Synchronised Cursors"/>
                <!-- temporarily remove "Pick" interaction for Lego until it is implemented
                <Panel screenName="Pick"       fileName="Pick"           toolTip="Show Info for Picked Item"/>
                -->
            </InteractionControl>

            <InteractionControl projectionName="TrackResidual" availableInDemoMode="NO">
                <Panel screenName="Pick"       fileName="Pick"           toolTip="Show Info for Picked Item"/>
            </InteractionControl>

            <InteractionControl projectionName="N3D">
                <Panel screenName="Rotate"        fileName="NZMR"       	 toolTip="Zoom/Move/Rotate"/>
            </InteractionControl>
            
            <InteractionControl projectionName="NYX">
            </InteractionControl>

           <InteractionControl projectionName="NPhysics">
                <Panel screenName="Rotate"        fileName="NZMR"       	 toolTip="Zoom/Move/Rotate"/>
           </InteractionControl>
           <InteractionControl projectionName="EventInfo">
           </InteractionControl>
             
 
        </Interactions>

        <Canvas startupLayout="FOUR SQUARES" aspectRatio="1.0">

            <UsedWindow name="1" projection="YX" group="Data"/>
            <UsedWindow name="2" projection="YX" group="Data"/>
            <UsedWindow name="3" projection="FZ" group="Data"/>
            <UsedWindow name="4" projection="YX" group="Data"/>
            <UsedWindow name="5" projection="RZ" group="null"/>
            <UsedWindow name="6" projection="VP" group="null"/>
            <UsedWindow name="7" projection="XZ" group="null"/>
            <UsedWindow name="8" projection="VP" group="null"/>
            <UsedWindow name="9" projection="LegoPlot" group="null"/>
            <UsedWindow name="L" projection="YX" group="null"/>
            <UsedWindow name="M" projection="RZ" group="null"/>
            <UsedWindow name="R" projection="VP" group="null"/>
            <UsedWindow name="U" projection="YX" group="null"/>
            <UsedWindow name="C" projection="FR" group="null"/>
            <UsedWindow name="D" projection="RZ" group="null"/>
            <UsedWindow name="E" projection="FZ" group="null"/>
            <UsedWindow name="S" projection="YX" group="null"/>
            <UsedWindow name="W" projection="YX" group="Data"/>
            <UsedWindow name="B" projection="RZ" group="Det"/>

            <Layout name="LANDSCAPE" startup="S36" startupWindow="S">
                <Window name="1" hPos="0" vPos="0" width="1" height="1"/>
                <Window name="2" hPos="1" vPos="0" width="1" height="1"/>
                <Window name="3" hPos="2" vPos="0" width="1" height="1"/>
                <Window name="4" hPos="0" vPos="1" width="1" height="1"/>
                <Window name="5" hPos="1" vPos="1" width="1" height="1"/>
                <Window name="6" hPos="2" vPos="1" width="1" height="1"/>
                <Window name="L" hPos="0" vPos="0" width="1" height="2"/>
                <Window name="M" hPos="1" vPos="0" width="1" height="2"/>
                <Window name="R" hPos="2" vPos="0" width="1" height="2"/>
                <Window name="U" hPos="0" vPos="0" width="2" height="1"/>
                <Window name="B" hPos="0" vPos="1" width="2" height="1"/>
                <Window name="S" hPos="0" vPos="0" width="2" height="2"/>
                <Window name="W" hPos="0" vPos="0" width="3" height="2"/>

                <Page name="Full" content="123456"/>
                <Page name="Vert" content="LMR"/>
                <Page name="Rect" content="SR"/>
                <Page name="Hori" content="UBR"/>
                <Page name="W"    content="W"/>
            </Layout>

            <Layout name="PORTRAIT" startup="SB" startupWindow="S">
                <Window name="1" hPos="0" vPos="0" width="1" height="1"/>
                <Window name="2" hPos="1" vPos="0" width="1" height="1"/>
                <Window name="3" hPos="0" vPos="1" width="1" height="1"/>
                <Window name="4" hPos="1" vPos="1" width="1" height="1"/>
                <Window name="5" hPos="0" vPos="2" width="1" height="1"/>
                <Window name="6" hPos="1" vPos="2" width="1" height="1"/>
                <Window name="U" hPos="0" vPos="0" width="2" height="1"/>
                <Window name="C" hPos="0" vPos="1" width="2" height="1"/>
                <Window name="B" hPos="0" vPos="2" width="2" height="1"/>
                <Window name="S" hPos="0" vPos="0" width="2" height="2"/>
                <Window name="W" hPos="0" vPos="0" width="2" height="3"/>
				
                <Page name="Full" content="123456"/>
                <Page name="Rect" content="SB"/>
                <Page name="Hori" content="UCB"/>
                <Page name="W"    content="W"/>
            </Layout>

            <Layout name="SQUARE B" startup="S369" startupWindow="S">
                <Window name="1" hPos="0" vPos="0" width="1" height="1"/>
                <Window name="2" hPos="1" vPos="0" width="1" height="1"/>
                <Window name="3" hPos="2" vPos="0" width="1" height="1"/>
                <Window name="4" hPos="0" vPos="1" width="1" height="1"/>
                <Window name="5" hPos="1" vPos="1" width="1" height="1"/>
                <Window name="6" hPos="2" vPos="1" width="1" height="1"/>
                <Window name="7" hPos="0" vPos="2" width="1" height="1"/>
                <Window name="8" hPos="1" vPos="2" width="1" height="1"/>
                <Window name="9" hPos="2" vPos="2" width="1" height="1"/>
                <Window name="W" hPos="0" vPos="0" width="3" height="3"/>
                <Window name="S" hPos="0" vPos="0" width="2" height="3"/>
                <Window name="L" hPos="0" vPos="0" width="1" height="3"/>
                <Window name="M" hPos="1" vPos="0" width="1" height="3"/>
                <Window name="R" hPos="2" vPos="0" width="1" height="3"/>
                <Window name="U" hPos="0" vPos="0" width="3" height="1"/>
                <Window name="C" hPos="0" vPos="1" width="3" height="1"/>
                <Window name="B" hPos="0" vPos="2" width="3" height="1"/>
                
                <Page name="Full" content="123456789"/>
                <Page name="Rect" content="SR"/>
                <Page name="Hori" content="LMR"/>
                <Page name="Vert" content="UCB"/>
                <Page name="W"    content="W"/>
            </Layout>

            <Layout name="SQUARE" startup="SRB" startupWindow="S">
                <Window name="1" hPos="0" vPos="0" width="1" height="1"/>
                <Window name="2" hPos="1" vPos="0" width="1" height="1"/>
                <Window name="3" hPos="2" vPos="0" width="1" height="1"/>
                <Window name="4" hPos="0" vPos="1" width="1" height="1"/>
                <Window name="5" hPos="1" vPos="1" width="1" height="1"/>
                <Window name="6" hPos="2" vPos="1" width="1" height="1"/>
                <Window name="7" hPos="0" vPos="2" width="1" height="1"/>
                <Window name="8" hPos="1" vPos="2" width="1" height="1"/>
                <Window name="9" hPos="2" vPos="2" width="1" height="1"/>
                <Window name="S" hPos="0" vPos="0" width="2" height="2"/>
                <Window name="L" hPos="0" vPos="0" width="1" height="2"/>
                <Window name="M" hPos="1" vPos="0" width="1" height="2"/>
                <Window name="R" hPos="2" vPos="0" width="1" height="2"/>
                <Window name="U" hPos="0" vPos="0" width="2" height="1"/>
                <Window name="C" hPos="0" vPos="1" width="2" height="1"/>
                <Window name="D" hPos="0" vPos="2" width="2" height="1"/>
                <Window name="B" hPos="0" vPos="2" width="3" height="1"/>
                <Window name="W" hPos="0" vPos="0" width="3" height="3"/>
                
                <Page name="Full" content="123456789"/>
                <Page name="Hori" content="LMRB"/>
                <Page name="Vert" content="UCD369"/>
                <Page name="All"  content="SRB"/>
                <Page name="W"    content="W"/>
            </Layout>

            <Layout name="FOUR SQUARES" startup="21B" startupWindow="B">
                <Window name="1" hPos="0" vPos="0" width="1" height="1"/>
                <Window name="2" hPos="1" vPos="0" width="1" height="1"/>
                <Window name="3" hPos="0" vPos="1" width="1" height="1"/>
                <Window name="4" hPos="1" vPos="1" width="1" height="1"/>
                <Window name="B" hPos="0" vPos="1" width="2" height="1"/>
                <Window name="W" hPos="0" vPos="0" width="2" height="2"/>
                
                <Page name="Four" content="1234"/>
                <Page name="Three" content="12B"/>
                <Page name="W"    content="W"/>
            </Layout>
            
            <Layout name="FULL SCREEN" startup="SRD" startupWindow="S">
                <Window name="S" hPos="0" vPos="0" width="2" height="2"/>
                <Window name="R" hPos="2" vPos="0" width="1" height="1"/>
                <Window name="D" hPos="2" vPos="1" width="1" height="1"/>
                <Window name="E" hPos="2" vPos="0" width="1" height="2"/>
                <Window name="L" hPos="0" vPos="0" width="1" height="1"/>
                <Window name="M" hPos="1" vPos="0" width="1" height="1"/>
                <Window name="B" hPos="0" vPos="1" width="2" height="1"/>
                <Window name="W" hPos="0" vPos="0" width="3" height="2"/>

                <Page name="Two" content="SE"/>
                <Page name="Three" content="SRD"/>
                <Page name="Five" content="LMRBD"/>
                <Page name="W"	  content="W"/>
            </Layout>

        </Canvas>

    </Initialization>

    
    <!-- assign userlevel for required configuration of Atlantis -->
    <Parameters userLevel="&user;">

        <SuperGroup name="Projection" toolTip="Projection Selection">

            <Group name="Projection" scope="LOCAL" toolTip="Projection Parameters">
                <FLOAT  fn="Radius" va="1320.0" pv="0:inf" tip="default detector radius" ul="&user;" u="&length;"/>
                <FLOAT  fn="Length" va="2250.0" pv="0:inf" tip="default detector length" ul="&user;" u="&length;"/>
                <FLOAT  fn="TrackingRadius" va="1320.0" pv="0:inf" tip="default detector radius" ul="&user;" u="&length;"/>
                <FLOAT  fn="TrackingLength" va="2250.0" pv="0:inf" tip="default detector length" ul="&user;" u="&length;"/>
                <FLOAT  fn="Energy Max" va="1000.0" pv="1:inf" ul="&debug;" u="&energy;"/>
                <STATUS fn="Skip Data" st="OFF" tip="Skip drawing of data during interaction if F key down"/>
            </Group>

            <Group name="YX" scope="LOCAL" guiUsage="PROJECTION" toolTip="YX Projection">
                <ENUM   fn="Mode" sn="View" va="0" pv="&modesYX;" ul="&user;" tip="View Mode"/>
				<ENUM   fn="LArBin" sn="Summed LAr binning" va="1" pv="0.1x0.1=1,0.2x0.2=2,split=3" tip="Shows the binning for the LAr Summed endcap view for &eta; and &phi;" scope="GLOBAL"/>
                <ENUM   fn="HECBin" sn="Summed HEC binning" va="2" pv="0.1x0.1=1,0.2x0.2=2,split=3" tip="Shows the binning for the HEC Summed endcap view for &eta; and &phi;" scope="GLOBAL"/>
                <FLOAT  fn="SplitEta" sn="Eta of split binning" va="2.5" pv="0:inf" tip="On summed binning seperates the split binning 0.1x0.1 below eta and 0.2x0.2 above eta, minimum 1.2 and only keeps 1 decimal place"/>
                <STATUS fn="DrawFCAL" sn="Draw FCAL inside HEC" st="OFF" tip="Draws the FCAL layers inside the relevant individual layers of the HEC (2,3,4)" scope="GLOBAL"/>
                <SLINT  fn="CSC Gas Gap" va="1" pv="1:4" st="OFF" ul="&user;" tip="Gas Gap in Cathode Strip Chambers"/>
                <SLINT  fn="TGC Gas Gap" va="1" pv="1:3" st="OFF" ul="&user;" tip="Gas Gap in Thin Gap Chambers"/>
                <FLOAT  fn="Phi" sn="&phi; for Clock interaction" va="0.0" pv="0:360" tip="&phi; angle for clock zoom interaction (Clock interaction must be activated)" ul="&superuser;"/>
                <SFLOAT fn="FishEye" va="1.5" pv="0:inf" st="ON" tip="Fish Eye zoom factor value" ul="&debug;"/>
                <SFLOAT fn="Clock" va="3.0" pv="0:inf" st="OFF" tip="Clock zoom factor value" ul="&debug;"/>
                <FLOAT  fn="rTo" sn="&rho; To" va="1100.0" pv="0:inf" tip="&rho; value for Fish Eye zoom (interaction)" ul="&debug;" u="&length;"/>
                <STATUS fn="RZ Cutting Plane" sn="&rho;Z Cutting Plane" st="OFF" tip="Show cutting plane of projection &rho;Z"/>
            </Group>

            <Group name="VP" sname="&phi;&eta;" scope="LOCAL" guiUsage="PROJECTION" toolTip="&phi;&eta; Projection">
                <Command name="Set Original Primary Vertex" command="SETORIGINALPRIMARYVERTEX" toolTip="Set original primary vertex of the current event" ul="&user;"/>